version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sergh2209Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: AddIntsPackage
  version: "1.0"
  gitServerName: srcCtrl_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/AddIntsPackage/_git
  gitUsername: ArtiKhare
  gitBranch: master
- name: substractpackage
  version: "2.0"
  gitServerName: src_shared_GitLabCtrl_Arti
  gitUrl: https://gitlab.com/ArtiKhareGitlabnew
  gitUsername: ArtiKhareGitlabnew
  gitBranch: master
services:
- serviceName: project.sergh2209.integrations:gitlabfs
  packages:
  - name: Sergh2209Project
    version: "1.0"
  - name: AddIntsPackage
    version: "1.0"
  - name: substractpackage
    version: "2.0"
- serviceName: SubstractPackage:substractFS
  packages:
  - name: substractpackage
    version: "2.0"
- serviceName: pub.math:subtractInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
